/**
 * Alteration status
 */

export const ALTERATION_REQUEST = "ALTERATION_REQUEST"
export const ALTERATION_SUCCESS = "ALTERATION_SUCCESS"
export const ALTERATION_FAILURE = "ALTERATION_FAILURE"
export const ALTERATION_CLEAR = "ALTERATION_CLEAR"
